services:
  mysql:
    image: mysql:8.0
    container_name: shopee-mini-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: shopee_mini
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    networks:
      - shopee-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shopee-mini-backend
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: shopee_mini
      DB_USERNAME: app
      DB_PASSWORD: app
      APP_ENV: production
      APP_URL: http://localhost:8000
      JWT_SECRET: super-secret-key-change-in-production-2026
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
    networks:
      - shopee-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shopee-mini-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://minishop-ea3l.onrender.com/api
    ports:
      - "4000:4000"
    depends_on:
      - backend
    networks:
      - shopee-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: shopee-mini-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: app
      PMA_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - shopee-network

volumes:
  mysql_data:

networks:
  shopee-network:
    driver: bridge
